In [3]:
import sys
import pandas as pd

In [4]:
sys.path.append("../src")  # Ajusta la ruta según dónde está tu notebook
from parser import parse_csv

# df = parse_csv('../data/data.csv')
df = pd.read_csv("../data/data.csv", encoding="utf-8")
print(df.columns)

Index(['IndicatorCode', 'Indicator', 'ValueType', 'ParentLocationCode',
       'ParentLocation', 'Location type', 'SpatialDimValueCode', 'Location',
       'Period type', 'Period', 'IsLatestYear', 'Dim1 type', 'Dim1',
       'Dim1ValueCode', 'Dim2 type', 'Dim2', 'Dim2ValueCode', 'Dim3 type',
       'Dim3', 'Dim3ValueCode', 'DataSourceDimValueCode', 'DataSource',
       'FactValueNumericPrefix', 'FactValueNumeric', 'FactValueUoM',
       'FactValueNumericLowPrefix', 'FactValueNumericLow',
       'FactValueNumericHighPrefix', 'FactValueNumericHigh', 'Value',
       'FactValueTranslationID', 'FactComments', 'Language', 'DateModified'],
      dtype='object')

In [5]:
df

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,EUR,Europe,Country,ALB,Albania,Year,2021,...,NaN,NaN,6.9,NaN,15.1,10.0 [6.9-15.1],NaN,"For this geography and year, some non-communic...",EN,2024-12-18T05:00:00.000Z
1,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,EUR,Europe,Country,TUR,Türkiye,Year,2021,...,NaN,NaN,6.4,NaN,13.3,10.1 [6.4-13.3],NaN,"For this geography and year, some non-communic...",EN,2024-12-18T05:00:00.000Z
2,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,AMR,Americas,Country,PRI,Puerto Rico,Year,2021,...,NaN,NaN,7.6,NaN,12.6,10.1 [7.6-12.6],NaN,"For this geography and year, some non-communic...",EN,2024-12-18T05:00:00.000Z
3,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,WPR,Western Pacific,Country,AUS,Australia,Year,2021,...,NaN,NaN,8.3,NaN,11.9,10.1 [8.3-11.9],NaN,NaN,EN,2024-12-18T05:00:00.000Z
4,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,EUR,Europe,Country,FRA,France,Year,2021,...,NaN,NaN,8.1,NaN,12.0,10.2 [8.1-12.0],NaN,NaN,EN,2024-12-18T05:00:00.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12205,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,EUR,Europe,Country,CYP,Cyprus,Year,2000,...,NaN,NaN,6.6,NaN,13.0,9.3 [6.6-13.0],NaN,NaN,EN,2024-12-18T05:00:00.000Z
12206,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,EUR,Europe,Country,ITA,Italy,Year,2000,...,NaN,NaN,8.6,NaN,9.8,9.3 [8.6-9.8],NaN,NaN,EN,2024-12-18T05:00:00.000Z
12207,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,EUR,Europe,Country,GRC,Greece,Year,2000,...,NaN,NaN,8.6,NaN,11.4,9.7 [8.6-11.4],NaN,NaN,EN,2024-12-18T05:00:00.000Z
12208,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,WPR,Western Pacific,Country,AUS,Australia,Year,2000,...,NaN,NaN,8.4,NaN,11.2,9.8 [8.4-11.2],NaN,NaN,EN,2024-12-18T05:00:00.000Z
12209,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,EUR,Europe,Country,FIN,Finland,Year,2000,...,NaN,NaN,8.4,NaN,11.3,9.8 [8.4-11.3],NaN,NaN,EN,2024-12-18T05:00:00.000Z

In [10]:
df["Location"].value_counts()

Location
Albania        66
Türkiye        66
Puerto Rico    66
Australia      66
France         66
               ..
Luxembourg     66
Israel         66
Sweden         66
Norway         66
Iceland        66
Name: count, Length: 185, dtype: int64

In [9]:
df["Dim1"].unique()

array(['Both sexes', 'Female', 'Male'], dtype=object)

In [11]:
countries = ["Singapore", "Switzerland", "Spain", "Japan", "Republic of Korea"]
available = [country for country in countries if country in df["Location"].unique()]
print("Países disponibles:", available)

Países disponibles: ['Singapore', 'Switzerland', 'Spain', 'Japan', 'Republic of Korea']